[database]
host = "postgres"
port = 5432
user = "postgres"
password = "postgres"
database = "conduit"

[http]
host = "0.0.0.0"
port = 8080

[ssh]
host = "0.0.0.0"
port = 8022
host_key = "data/ssh_host_ed25519_key"
