[build]
rustflags = ["--cfg", "tokio_unstable"]

[profile.dev]
debug = "line-tables-only"

[profile.ci]
inherits = "dev"
incremental = false

[profile.release]
opt-level = "s"
lto = "thin"
codegen-units = 1

[target.x86_64-unknown-linux-gnu]
rustflags = ["--cfg", "tokio_unstable", "-C", "target_cpu=x86-64-v3"]
